name: CI
on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: Use Node.js latest
        uses: actions/setup-node@4
        with:
          node-version: lts

      - name: Setup pnpm
        uses: pnpm/action-setup@latest
        with:
          version: latest

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: Debbl/tools.aiwan.run
          exclude_assets: ".github, .nojekyll"
          publish_branch: main
          publish_dir: out
          destination_dir: code-diff
